### ISSUE TITLE
Schnittstelle zur Buchhaltungssoftware

### ISSUE THREAD

**Issue by R4V3NN0** [R4V3NN0/sharing.ly#11]
### Idee wie sie aussehen könnte
Man könnte in der Kundendatenbank den Namen und die Kontodaten speichern.

Dann würden wir nämlich 

- Name
- Kontodaten
- Preis
- Verwendungszweck wo auch die Buchungsdaten drin stehen
- Zeitraum

an die Software senden, damit diese eine Rechnung erstellen kann.

**Comment by TuncerCatalkaya** [comment]
Kontodaten = Bankverbindung

**Comment by R4V3NN0** [comment]
Geeinigt auf:
-Bankverbindung
-Preis
-Zeitraum
-gewähltes Fahrzeug
-Name
